from setuptools import setup, find_packages
import os

# Define requirements directly (Linux-compatible)
requirements = [
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.13",
    "aiosignal==1.3.2",
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "asttokens==3.0.0",
    "attrs==25.3.0",
    "backcall==0.2.0",
    "beautifulsoup4==4.13.4",
    "bleach==6.2.0",
    "certifi==2025.6.15",
    "cffi==1.17.1",
    "charset-normalizer==3.4.2",
    "colorama==0.4.6",
    "cryptography==45.0.4",
    "dataclasses-json==0.6.7",
    "decorator==5.2.1",
    "defusedxml==0.7.1",
    "demjson3==3.0.6",
    "distro==1.9.0",
    "docopt==0.6.2",
    "executing==2.2.0",
    "fastjsonschema==2.21.1",
    "frozenlist==1.7.0",
    "greenlet==3.2.3",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "httpx-sse==0.4.1",
    "idna==3.10",
    "ipython==8.12.3",
    "jedi==0.19.2",
    "Jinja2==3.1.6",
    "jiter==0.10.0",
    "jsonpatch==1.33",
    "jsonpointer==3.0.0",
    "jsonschema==4.24.0",
    "jsonschema-specifications==2025.4.1",
    "jupyter_client==8.6.3",
    "jupyter_core==5.8.1",
    "jupyterlab_pygments==0.3.0",
    "langchain==0.3.26",
    "langchain-community==0.3.26",
    "langchain-core==0.3.66",
    "langchain-openai==0.3.27",
    "langchain-text-splitters==0.3.8",
    "langsmith==0.4.4",
    "MarkupSafe==3.0.2",
    "marshmallow==3.26.1",
    "matplotlib-inline==0.1.7",
    "mistune==3.1.3",
    "multidict==6.6.2",
    "mypy_extensions==1.1.0",
    "nbclient==0.10.2",
    "nbconvert==7.16.6",
    "nbformat==5.10.4",
    "numpy==2.3.1",
    "openai==1.93.0",
    "orjson==3.10.18",
    "packaging==24.2",
    "pandocfilters==1.5.1",
    "parso==0.8.4",
    "pdfminer.six==20250506",
    "pickleshare==0.7.5",
    "platformdirs==4.3.8",
    "prompt_toolkit==3.0.51",
    "propcache==0.3.2",
    "pure_eval==0.2.3",
    "pycparser==2.22",
    "pydantic==2.11.7",
    "pydantic-settings==2.10.1",
    "pydantic_core==2.33.2",
    "Pygments==2.19.2",
    "PyMuPDF==1.26.1",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.1",
    "python-env==1.0.0",
    "PyYAML==6.0.2",
    "pyzmq==27.0.0",
    "referencing==0.36.2",
    "regex==2024.11.6",
    "requests==2.32.4",
    "requests-toolbelt==1.0.0",
    "rpds-py==0.25.1",
    "six==1.17.0",
    "sniffio==1.3.1",
    "soupsieve==2.7",
    "SQLAlchemy==2.0.41",
    "stack-data==0.6.3",
    "tenacity==9.1.2",
    "termcolor==2.3.0",
    "tiktoken==0.9.0",
    "tinycss2==1.4.0",
    "tornado==6.5.1",
    "tqdm==4.67.1",
    "traitlets==5.14.3",
    "typing-inspect==0.9.0",
    "typing-inspection==0.4.1",
    "typing_extensions==4.14.0",
    "urllib3==2.5.0",
    "wcwidth==0.2.13",
    "webencodings==0.5.1",
    "yarg==0.1.9",
    "yarl==1.20.1",
    "yaspin==3.1.0",
    "zstandard==0.23.0"
]

# Read the README file
def read_readme():
    readme_path = os.path.join(os.path.dirname(__file__), 'README.md')
    try:
        with open(readme_path, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return "LLM-based Sri Lankan Government Gazette Data Extraction Tool"

setup(
    name="gztextractor",
    version="1.0.0",
    author="Isuru Rangana",
    author_email="isuru.rangana@example.com",
    description="LLM-based Sri Lankan Government Gazette Data Extraction Tool",
    long_description=read_readme(),
    long_description_content_type="text/markdown",
    url="https://github.com/Isuru-rangana/gazzetExtractor1",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Text Processing",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.8",
    install_requires=requirements,
    entry_points={
        "console_scripts": [
            "gztextractor=gztextractor.cli:main",
        ],
    },
    include_package_data=True,
    package_data={
        "gztextractor": [
            "assets/pdf/*.pdf",
        ],
    },
    zip_safe=False,
)
